main = "dist/index.js"

compatibility_date = "2024-08-26"
compatibility_flags = [ "nodejs_compat" ]

[env.dev]
vars = { ALLOWED_HOST = "*", ENV = "dev" }
[[env.dev.kv_namespaces]]
binding = "LOCAL_DB"
id = "local-db"

[env.test]
vars = { ALLOWED_HOST = "*", ENV = "test" }
[[env.test.kv_namespaces]]
binding = "TEST_DB"
id = "test-db"

[env.stage]
name = "simon-stage"
workers_dev = true
vars = { ALLOWED_HOST = "simon-evn.pages.dev", ENV = "stage" }
[[env.stage.kv_namespaces]]
binding = "DB"
id = "73d1493b972c4fd2a28f53c55feae408"

[env.prod]
name = "simon"
workers_dev = true
vars = { ALLOWED_HOST = "simon.codenickycode.com", ENV = "prod" }
[[env.prod.kv_namespaces]]
binding = "DB"
id = "420d2dc5d82e4ce197d82de18946be4b"
