name = "simon"
main = "dist/index.js"

compatibility_date = "2024-08-26"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = true

[vars]
ALLOWED_ORIGIN = 'https://simon.codenickycode.com'
ENV = 'prod'

[[kv_namespaces]]
binding = "DB"
id = "420d2dc5d82e4ce197d82de18946be4b"